INSERT INTO TopicProp VALUES ('pp-active', 1, 'Name', 'Active');
INSERT INTO TopicProp VALUES ('pp-associationtypeid', 1, 'Name', 'Association Type ID');
INSERT INTO TopicProp VALUES ('pp-backgroundimage', 1, 'Name', 'Background Image');
INSERT INTO TopicProp VALUES ('pp-bgcolor', 1, 'Name', 'Background Color');
INSERT INTO TopicProp VALUES ('pp-birthday', 1, 'Name', 'Birthday');
INSERT INTO TopicProp VALUES ('pp-cardinality', 1, 'Name', 'Cardinality');
INSERT INTO TopicProp VALUES ('pp-chatarea', 1, 'Name', 'Chat Flow');
INSERT INTO TopicProp VALUES ('pp-clientname', 1, 'Name', 'Client Name');
INSERT INTO TopicProp VALUES ('pp-color', 1, 'Name', 'Color');
INSERT INTO TopicProp VALUES ('pp-corporateworkgroup', 1, 'Name', 'Default');
INSERT INTO TopicProp VALUES ('pp-createpermission', 1, 'Name', 'Access Permission');
INSERT INTO TopicProp VALUES ('pp-creationicon', 1, 'Name', 'Creation Icon');
INSERT INTO TopicProp VALUES ('pp-customericon', 1, 'Name', 'Customer Icon');
INSERT INTO TopicProp VALUES ('pp-descriptionquery', 1, 'Name', 'Description Query');
INSERT INTO TopicProp VALUES ('pp-disabled', 1, 'Name', 'Disabled');
INSERT INTO TopicProp VALUES ('pp-domaininfo', 1, 'Name', 'Domain Information');
INSERT INTO TopicProp VALUES ('pp-downloading', 1, 'Name', 'Loading');
INSERT INTO TopicProp VALUES ('pp-duration', 1, 'Name', 'Duration');
INSERT INTO TopicProp VALUES ('pp-editicon', 1, 'Name', 'Edit Icon');
INSERT INTO TopicProp VALUES ('pp-elementcount', 1, 'Name', 'ElementCount');
INSERT INTO TopicProp VALUES ('pp-entities', 1, 'Name', 'Entities');
INSERT INTO TopicProp VALUES ('pp-file', 1, 'Name', 'File');
INSERT INTO TopicProp VALUES ('pp-geometrylocked', 1, 'Name', 'Locked Geometry');
INSERT INTO TopicProp VALUES ('pp-hideinstancenames', 1, 'Name', 'Hidden Topic Names');
INSERT INTO TopicProp VALUES ('pp-icon', 1, 'Name', 'Icon');
INSERT INTO TopicProp VALUES ('pp-idleelementtype', 1, 'Name', 'Idle Elementtype');
INSERT INTO TopicProp VALUES ('pp-implementingclass', 1, 'Name', 'Custom Implementation');
INSERT INTO TopicProp VALUES ('pp-info', 1, 'Name', 'Description');
INSERT INTO TopicProp VALUES ('pp-infosingle', 1, 'Name', 'Description');
INSERT INTO TopicProp VALUES ('pp-language', 1, 'Name', 'Language');
INSERT INTO TopicProp VALUES ('pp-name', 1, 'Name', 'Name');
INSERT INTO TopicProp VALUES ('pp-ordinalnumber', 1, 'Name', 'Ordinal Number');
INSERT INTO TopicProp VALUES ('pp-parsing', 1, 'Name', 'Parsing');
INSERT INTO TopicProp VALUES ('pp-password', 1, 'Name', 'Password');
INSERT INTO TopicProp VALUES ('pp-passwordattr', 1, 'Name', 'Password Attribute');
INSERT INTO TopicProp VALUES ('pp-pluraltypename', 1, 'Name', 'Plural Name');
INSERT INTO TopicProp VALUES ('pp-profileelementtype', 1, 'Name', 'Profile Elementtype');
INSERT INTO TopicProp VALUES ('pp-queryelements', 1, 'Name', 'QueryElements');
INSERT INTO TopicProp VALUES ('pp-relatedtopicid', 1, 'Name', 'RelatedTopicID');
INSERT INTO TopicProp VALUES ('pp-serviceicon', 1, 'Name', 'Corporate Icon');
INSERT INTO TopicProp VALUES ('pp-servicename', 1, 'Name', 'Server Name');
INSERT INTO TopicProp VALUES ('pp-settings', 1, 'Name', 'Settings');
INSERT INTO TopicProp VALUES ('pp-showbuildpanel', 1, 'Name', 'Show build panel');
INSERT INTO TopicProp VALUES ('pp-showsidebar', 1, 'Name', 'Show side panel');
INSERT INTO TopicProp VALUES ('pp-splitscreen', 1, 'Name', 'Splitted screen');
INSERT INTO TopicProp VALUES ('pp-starttime', 1, 'Name', 'Begin');
INSERT INTO TopicProp VALUES ('pp-starturl', 1, 'Name', 'Start URL');
INSERT INTO TopicProp VALUES ('pp-statistics', 1, 'Name', 'Statistics');
INSERT INTO TopicProp VALUES ('pp-subscribable', 1, 'Name', 'Public');
INSERT INTO TopicProp VALUES ('pp-topicname', 1, 'Name', 'Topic Name');
INSERT INTO TopicProp VALUES ('pp-translationUse', 1, 'Name', 'Translation');
INSERT INTO TopicProp VALUES ('pp-unique', 1, 'Name', 'Unique Topic Names');
INSERT INTO TopicProp VALUES ('pp-url', 1, 'Name', 'URL');
INSERT INTO TopicProp VALUES ('pp-userentry', 1, 'Name', 'Your Remark');
INSERT INTO TopicProp VALUES ('pp-visualization', 1, 'Name', 'Visualization');
