<%@ page import="de.deepamehta.BaseTopic" %>
<%@ page import="de.deepamehta.PresentableTopic" %>
<%@ page import="de.deepamehta.TopicGeometry" %>
<%@ page import="de.deepamehta.service.web.HTMLGenerator" %>

<%@ page import="de.deepamehta.topicmapviewer.TopicmapViewer" %>

<%@ page import="java.io.IOException" %>
<%@ page import="java.util.Date" %>
<%@ page import="java.util.Enumeration" %>
<%@ page import="java.util.Vector" %>
<%@ page import="java.util.Hashtable" %>

<%!
	void begin(HttpSession session, JspWriter out) throws IOException {
		out.println("<html>\r<head>\r<title>DeepaMehta</title>\r</head>\r<body>\r");
	}

	void end(HttpSession session, JspWriter out) throws IOException {
		out.println("<br><p>\r<hr>\r<small>Generated by DeepaMehta on " + new Date() + "</small>\r</body>\r</html>");
	}
%>
