-- The table and schema names have to be UPPER CASE!

CALL SYSCS_UTIL.SYSCS_COMPRESS_TABLE('DEEPAMEHTA', 'TOPIC', 1);
CALL SYSCS_UTIL.SYSCS_COMPRESS_TABLE('DEEPAMEHTA', 'ASSOCIATION', 1);
CALL SYSCS_UTIL.SYSCS_COMPRESS_TABLE('DEEPAMEHTA', 'VIEWTOPIC', 1);
CALL SYSCS_UTIL.SYSCS_COMPRESS_TABLE('DEEPAMEHTA', 'VIEWASSOCIATION', 1);
CALL SYSCS_UTIL.SYSCS_COMPRESS_TABLE('DEEPAMEHTA', 'TOPICPROP', 1);
CALL SYSCS_UTIL.SYSCS_COMPRESS_TABLE('DEEPAMEHTA', 'ASSOCIATIONPROP', 1);
CALL SYSCS_UTIL.SYSCS_COMPRESS_TABLE('DEEPAMEHTA', 'KEYGENERATOR', 1);
