INSERT INTO Movie VALUES (1, 'Ed Wood', '', 1, 'USA', '1994', '2:06');
INSERT INTO Movie VALUES (2, 'Erbarmungslos', 'Unforgiven', 2, 'USA', '1992', '2:00');
INSERT INTO Movie VALUES (3, 'Before Sunrise', '', 3, 'USA/A', '1994', '1:37');
INSERT INTO Movie VALUES (4, 'Killing Zoe', '', 4, 'USA', '1994', '1:36');
INSERT INTO Movie VALUES (5, 'Rollerball', '', 5, 'USA', '1974', '2:05');
INSERT INTO Movie VALUES (6, 'The Saint', '', 4, 'USA', '1997', '1:56');
INSERT INTO Movie VALUES (7, 'Gilbert Grape', 'Whats Eating Gilbert Grape?', 6, 'USA', '1993', '1:57');
INSERT INTO Movie VALUES (8, '12 Monkeys', '', 0, 'USA', '1995', '2:09');
INSERT INTO Movie VALUES (9, 'Mikey und Nicky', '', 0, 'USA', '1976', '1:53');
INSERT INTO Movie VALUES (10, 'Casino', '', 0, 'USA', '1995', '2:45');
INSERT INTO Movie VALUES (11, 'Delicatessen', '', 0, 'F', '1990', '1:39');
INSERT INTO Movie VALUES (12, 'Snake Eyes', '', 0, 'USA', '1993', '1:47');
INSERT INTO Movie VALUES (13, 'Dead Man Walking', '', 0, 'USA', '1995', '2:02');
INSERT INTO Movie VALUES (14, 'Smoke', '', 0, 'USA', '1995', '1:48');

INSERT INTO Actor VALUES (1, 'Johnny Depp');
INSERT INTO Actor VALUES (2, 'Martin Landau');
INSERT INTO Actor VALUES (3, 'Sarah Jessica Parker');
INSERT INTO Actor VALUES (4, 'Clint Eastwood');
INSERT INTO Actor VALUES (5, 'Gene Hackman');
INSERT INTO Actor VALUES (6, 'Morgan Freeman');
INSERT INTO Actor VALUES (7, 'Ethan Hawke');
INSERT INTO Actor VALUES (8, 'Julie Delpy');
INSERT INTO Actor VALUES (9, 'Andrea Eckert');
INSERT INTO Actor VALUES (10, 'Eric Stoltz');
INSERT INTO Actor VALUES (11, 'Jean-Hugues Anglade');
INSERT INTO Actor VALUES (12, 'James Caan');
INSERT INTO Actor VALUES (13, 'John Houseman');
INSERT INTO Actor VALUES (14, 'John Beck');
INSERT INTO Actor VALUES (15, 'Val Kilmer');
INSERT INTO Actor VALUES (16, 'Elisabeth Shue');
INSERT INTO Actor VALUES (17, 'Rade Serbedzija');
INSERT INTO Actor VALUES (18, 'Juliette Lewis');
INSERT INTO Actor VALUES (19, 'Leonardo DiCaprio');

INSERT INTO Mitwirkung VALUES (1, 1);
INSERT INTO Mitwirkung VALUES (1, 2);
INSERT INTO Mitwirkung VALUES (1, 3);
INSERT INTO Mitwirkung VALUES (2, 4);
INSERT INTO Mitwirkung VALUES (2, 5);
INSERT INTO Mitwirkung VALUES (2, 6);
INSERT INTO Mitwirkung VALUES (3, 7);
INSERT INTO Mitwirkung VALUES (3, 8);
INSERT INTO Mitwirkung VALUES (3, 9);
INSERT INTO Mitwirkung VALUES (4, 10);
INSERT INTO Mitwirkung VALUES (4, 8);
INSERT INTO Mitwirkung VALUES (4, 11);
INSERT INTO Mitwirkung VALUES (5, 12);
INSERT INTO Mitwirkung VALUES (5, 13);
INSERT INTO Mitwirkung VALUES (5, 14);
INSERT INTO Mitwirkung VALUES (6, 15);
INSERT INTO Mitwirkung VALUES (6, 16);
INSERT INTO Mitwirkung VALUES (6, 17);
INSERT INTO Mitwirkung VALUES (7, 1);
INSERT INTO Mitwirkung VALUES (7, 18);
INSERT INTO Mitwirkung VALUES (7, 19);

INSERT INTO Gattung VALUES(1, 'Tragikkomoedie');
INSERT INTO Gattung VALUES(2, 'Western');
INSERT INTO Gattung VALUES(3, 'Liebesfilm');
INSERT INTO Gattung VALUES(4, 'Actionthriller');
INSERT INTO Gattung VALUES(5, 'Actionfilm');
INSERT INTO Gattung VALUES(6, 'Familiendrama');

